const payload1 = [
  {
    "Type": "sa_invoice",
    "Key": null,
    "RefType": 3560,
    "RefTypeCategory": 0,
    "View": "view_sa_invoice",
    "Details": [
      {
        "Type": "sa_invoice_detail",
        "Alias": "detail",
        "View": "view_sa_invoice_detail",
        "Objects": [
          {
            "ref_detail_id": crypto.randomUUID(),
            "inventory_item_id": "7e701878-63c6-41c6-b388-03f141355f40",
            "unit_id": "6ddcd5db-b9a3-42eb-b6aa-577456e93ddf",
            "main_unit_id": "6ddcd5db-b9a3-42eb-b6aa-577456e93ddf",
            "sort_order": 1,
            "is_promotion": false,
            "not_in_vat_declaration": false,
            "quantity": 1,
            "unit_price": 0,
            "unit_price_after_tax": 0,
            "amount_oc": 0,
            "amount": 0,
            "discount_rate": 0,
            "main_convert_rate": 1,
            "main_quantity": 1,
            "amount_after_tax": 0,
            "discount_amount_oc": 0,
            "discount_amount": 0,
            "vat_rate": -1,
            "vat_rate_406": 0,
            "deductions_tax_amount": 0,
            "deductions_tax_amount_oc": 0,
            "tmp_deductions_tax_amount": 0,
            "tmp_deductions_tax_amount_oc": 0,
            "vat_amount_oc": 0,
            "vat_amount": 0,
            "main_unit_price": 0,
            "description": "Tiếng Việt 1 tập 1 (Test API)",
            "exchange_rate_operator": "*",
            "inventory_item_code": "109284",
            "inventory_item_name": "Tiếng Việt 1 tập 1 (Cánh Diều)",
            "unit_name": "Quyển",
            "main_unit_name": "Quyển",
            "state": 1,
            "discount_type": 0,
            "is_follow_serial_number": false,
            "is_allow_duplicate_serial_number": false,
            "is_unit_price_after_tax": false,
            "purchase_last_unit_price_list": "[{\"currency_id\" : \"VND\", \"unit_id\" : \"6ddcd5db-b9a3-42eb-b6aa-577456e93ddf\", \"unit_name\" : \"Quyển\", \"unit_price\" : \"27000.0000\"}]",
            "isChange": true,
            "unitprice_sale": 0,
            "relation_detail_sa_voucher_invoice": [],
            "is_delete_relation_invoice_detail": true,
            "is_commercial_abatement": false,
            "inventory_item_type": 0,
            "item_discount_rate": 0,
            "invoice_discount_rate": 0,
            "item_discount_amount_oc": 0,
            "invoice_discount_amount_oc": 0,
            "item_discount_amount": 0,
            "invoice_discount_amount": 0,
            "quantity_in_combo": 0
          }
        ]
      }
    ],
    "Links": [],
    "Object": {
      "branch_id": "a4c49e6a-ccd7-413a-94b0-8349d1ccbb22",
      "account_object_id": "2e09a780-d17f-47a7-bff2-eef23ea3b9b6",
      "display_on_book": 0,
      "reftype": 3560,
      "inv_date": new Date().toISOString(),
      "is_paid": false,
      "is_posted": false,
      "include_invoice": 0,
      "is_attach_list": false,
      "is_branch_issued": false,
      "is_posted_last_year": false,
      "is_invoice_replace": false,
      "exchange_rate": 1,
      "total_sale_amount_oc": 0,
      "total_sale_amount": 0,
      "total_discount_amount_oc": 0,
      "total_discount_amount": 0,
      "total_vat_amount_oc": 0,
      "total_vat_amount": 0,
      "total_amount_oc": 0,
      "total_amount": 0,
      "account_object_name": "Khách lẻ",
      "account_object_address": "C39 khu C Geleximco, Dương Nội, Hà Đông",
      "payment_method": "TM/CK",
      "buyer": "Test Script",
      "currency_id": "VND",
      "discount_type": 0,
      "state": 1,
      "refdate": new Date().toISOString(),
      "account_object_code": "KLE",
      "publish_status": 0,
      "discount_rate_voucher": 0,
      "is_created_savoucher": 0,
      "send_email_status": 0,
      "invoice_status": 1,
      "voucher_reference": [],
      "attachment_id_list_data": [],
      "is_invoice_deleted": false,
      "is_follows_406": false,
      "publish_taxcode_status": 0,
      "tax_reduction_type": 0,
      "is_tax_reduction_type_43": false,
      "is_delete_voucher_reference": false,
      "is_discount_invoice": false,
      "dav_using_permision": true,
      "is_invoice_machine": false,
      "phone_number": "0398610020",
      "MappingEinvoiceObjectList": []
    },
    "auditing_log": {
      "id": null,
      "tenant_id": null,
      "refid": null,
      "user_id": null,
      "reftype": 3560,
      "login_name": null,
      "ip": null,
      "action": 1,
      "action_name": "Thêm",
      "reference": "Số hóa đơn: null",
      "description": "- Số dòng: 1 \n- Tổng số tiền: 0. (Test API)",
      "time": null,
      "state": 1,
      "object_name": "Hóa đơn bán hàng hóa, dịch vụ trong nước",
      "branch_name": "CÔNG TY CỔ PHẦN ĐẦU TƯ GIÁO DỤC BẮC TRUNG NAM",
      "is_inserting_log_into_another_db": null,
      "log_database_id": null,
      "securityactionid": null,
      "record_type": null,
      "index": 1,
      "isAuditingLog": true,
      "masterDescription": [],
      "isMultiMaster": false,
      "detailDescription": {
        "insert": [],
        "update": [],
        "delete": [],
        "custom": []
      }
    },
    "OptionForSave": {
      "PostAfterSave": true,
      "IsQuickEdit": false,
      "FormState": "Add"
    }
  }
];