const fullPayload = [
  {
    "Type": "sa_voucher",
    "Key": null,
    "RefType": 3530,
    "RefTypeCategory": 353,
    "View": "view_sa_voucher",
    "enableAutoSave": true,
    "Details": [
      {
        "Type": "sa_voucher_detail",
        "View": "view_sa_voucher_detail",
        "Alias": "detail",
        "UseRecover": true,
        "Objects": [
          {
            "account_object_address": "C39 Geleximco C",
            "account_object_id": "2e09a780-d17f-47a7-bff2-eef23ea3b9b6",
            "account_object_code": "KLE",
            "account_object_name": "Khách lẻ",
            "amount": 24100,
            "amount_finance": 0,
            "amount_management": 0,
            "amount_oc": 24100,
            "credit_account": "5111",
            "debit_account": "131",
            "description": "Tiếng Việt 1 tập 2 (Cánh Diều)",
            "discount_account": "5111",
            "discount_amount": 0,
            "discount_amount_oc": 0,
            "discount_rate": 0,
            "discount_type": 0,
            "exchange_rate_operator": "*",
            "inventory_item_id": "2460d91a-8524-48c1-b0a8-2db54ac13916",
            "inventory_item_code": "109285",
            "inventory_resale_type_id": 0,
            "main_convert_rate": 1,
            "main_quantity": 1,
            "main_unit_id": "6ddcd5db-b9a3-42eb-b6aa-577456e93ddf",
            "main_unit_name": "Quyển",
            "main_unit_price": 24100,
            "main_unit_price_finance": 0,
            "main_unit_price_management": 0,
            "panel_length_quantity": 0,
            "panel_width_quantity": 0,
            "panel_height_quantity": 0,
            "panel_radius_quantity": 0,
            "panel_quantity": 0,
            "quantity": 1,
            "ref_detail_id": "38ec763b-cbc7-485b-8320-5a65a7660b85",
            "sale_amount": 0,
            "sale_price": 0,
            "sort_order": 1,
            "state": 1,
            "stock_code": "KHN",
            "stock_id": "51a49d53-2fea-4e56-8cdd-bf41af64a0bf",
            "unit_id": "6ddcd5db-b9a3-42eb-b6aa-577456e93ddf",
            "unit_name": "Quyển",
            "unit_price": 24100,
            "unit_price_after_discount": 24100,
            "unit_price_after_tax": 0,
            "unit_price_finance": 0,
            "unit_price_management": 0,
            "vat_account": "33311",
            "vat_amount": 0,
            "vat_amount_oc": 0,
            "vat_rate": -1,
            "vat_rate_406": 0,
            "deductions_tax_amount": 0,
            "deductions_tax_amount_oc": 0,
            "tmp_deductions_tax_amount": 0,
            "tmp_deductions_tax_amount_oc": 0,
            "inventory_item_type": 0,
            "amount_after_tax": 0,
            "inventory_account": "156",
            "vat_description": "Thuế GTGT - Tiếng Việt 1 tập 2 (Cánh Diều)",
            "unitprice_sale": 24100,
            "cost_account": "632",
            "stock_account": "156",
            "cost_main_unit_price_finance": 0,
            "cost_amount_finance": 0,
            "cost_unit_price_finance": 0,
            "cost_amount_management": 0,
            "cost_unit_price_management": 0,
            "cost_main_unit_price_management": 0,
            "export_tax_rate": 0,
            "export_tax_amount": 0,
            "fob_amount": 0,
            "is_follow_serial_number": false,
            "is_allow_duplicate_serial_number": false,
            "is_open": true,
            "stock_name": "KHO HÀ NỘI",
            "is_unit_price_after_tax": false,
            "is_change": false,
            "purchase_last_unit_price_list": "[{\"currency_id\" : \"VND\", \"unit_id\" : \"6ddcd5db-b9a3-42eb-b6aa-577456e93ddf\", \"unit_name\" : \"Quyển\", \"unit_price\" : \"19521.0000\"}]",
            "allocation_time": 0,
            "allocation_type": 0,
            "inventory_item_name": "Tiếng Việt 1 tập 2 (Cánh Diều)",
            "unit_sell_divide_min": 0,
            "is_drug": false,
            "invoiced_quantity": 1,
            "exported_invoice_at_least_one": false,
            "relation_detail_sa_voucher_invoice": [],
            "is_delete_relation_invoice_detail": false,
            "sale_account": "5111",
            "is_combo": false,
            "combo_type": 0,
            "inventory_item_cost_method": -1,
            "item_discount_rate": 0,
            "invoice_discount_rate": 0,
            "item_discount_amount_oc": 0,
            "invoice_discount_amount_oc": 0,
            "item_discount_amount": 0,
            "invoice_discount_amount": 0,
            "serial_text": null,
            "serial_inward_list": null,
            "serial_define_list": null,
            "serial_text_tooltip": null,
            "list_ref_detail_id": [
              "38ec763b-cbc7-485b-8320-5a65a7660b85",
              "f02e9954-5817-4cb0-8aa2-903034652535",
              "38ec763b-cbc7-485b-8320-5a65a7660b85",
              "f02e9954-5817-4cb0-8aa2-903034652535"
            ]
          },
          {
            "account_object_address": "C39 Geleximco C",
            "account_object_id": "2e09a780-d17f-47a7-bff2-eef23ea3b9b6",
            "account_object_code": "KLE",
            "account_object_name": "Khách lẻ",
            "amount": 26900,
            "amount_finance": 0,
            "amount_management": 0,
            "amount_oc": 26900,
            "credit_account": "5111",
            "debit_account": "131",
            "description": "Toán 1 (Cánh Diều)",
            "discount_account": "5111",
            "discount_amount": 0,
            "discount_amount_oc": 0,
            "discount_rate": 0,
            "discount_type": 0,
            "exchange_rate_operator": "*",
            "inventory_item_id": "99d139f1-a938-4296-89e8-fd310f5f4809",
            "inventory_item_code": "109286",
            "inventory_resale_type_id": 0,
            "is_promotion": false,
            "main_convert_rate": 1,
            "main_quantity": 1,
            "main_unit_id": "6ddcd5db-b9a3-42eb-b6aa-577456e93ddf",
            "main_unit_name": "Quyển",
            "main_unit_price": 26900,
            "main_unit_price_finance": 0,
            "main_unit_price_management": 0,
            "not_in_vat_declaration": false,
            "panel_length_quantity": 0,
            "panel_width_quantity": 0,
            "panel_height_quantity": 0,
            "panel_radius_quantity": 0,
            "panel_quantity": 0,
            "quantity": 1,
            "ref_detail_id": "f02e9954-5817-4cb0-8aa2-903034652535",
            "sale_amount": 0,
            "sale_price": 0,
            "sort_order": 2,
            "state": 1,
            "stock_code": "KHN",
            "stock_id": "51a49d53-2fea-4e56-8cdd-bf41af64a0bf",
            "unit_id": "6ddcd5db-b9a3-42eb-b6aa-577456e93ddf",
            "unit_name": "Quyển",
            "unit_price": 26900,
            "unit_price_after_discount": 26900,
            "unit_price_after_tax": 0,
            "unit_price_finance": 0,
            "unit_price_management": 0,
            "vat_account": "33311",
            "vat_amount": 2152,
            "vat_amount_oc": 2152,
            "vat_rate": 8,
            "vat_rate_406": 0,
            "deductions_tax_amount": 538,
            "deductions_tax_amount_oc": 538,
            "tmp_deductions_tax_amount": 538,
            "tmp_deductions_tax_amount_oc": 538,
            "inventory_item_type": 0,
            "amount_after_tax": 0,
            "inventory_account": "156",
            "vat_description": "Thuế GTGT - Toán 1 (Cánh Diều)",
            "unitprice_sale": 26900,
            "cost_account": "632",
            "stock_account": "156",
            "cost_main_unit_price_finance": 0,
            "cost_amount_finance": 0,
            "cost_unit_price_finance": 0,
            "cost_amount_management": 0,
            "cost_unit_price_management": 0,
            "cost_main_unit_price_management": 0,
            "export_tax_rate": 0,
            "export_tax_amount": 0,
            "fob_amount": 0,
            "is_follow_serial_number": false,
            "is_allow_duplicate_serial_number": false,
            "is_open": true,
            "stock_name": "KHO HÀ NỘI",
            "is_unit_price_after_tax": false,
            "is_change": false,
            "is_description": false,
            "purchase_last_unit_price_list": "[{\"currency_id\" : \"VND\", \"unit_id\" : \"6ddcd5db-b9a3-42eb-b6aa-577456e93ddf\", \"unit_name\" : \"Quyển\", \"unit_price\" : \"26900.0000\"}]",
            "allocation_time": 0,
            "allocation_type": 0,
            "inventory_item_name": "Toán 1 (Cánh Diều)",
            "unit_sell_divide_min": 0,
            "is_drug": false,
            "invoiced_quantity": 1,
            "exported_invoice_at_least_one": false,
            "relation_detail_sa_voucher_invoice": [],
            "is_delete_relation_invoice_detail": false,
            "sale_account": "5111",
            "is_combo": false,
            "quantity_in_combo": 0,
            "combo_type": 0,
            "inventory_item_cost_method": -1,
            "is_from_meinvoice": false,
            "item_discount_rate": 0,
            "invoice_discount_rate": 0,
            "item_discount_amount_oc": 0,
            "invoice_discount_amount_oc": 0,
            "item_discount_amount": 0,
            "invoice_discount_amount": 0,
            "is_commercial_abatement": false,
            "serial_text": null,
            "serial_inward_list": null,
            "serial_define_list": null,
            "serial_text_tooltip": null
          }
        ]
      },
      {
        "Type": "sa_voucher_detail_allocation",
        "Alias": "detailOther1",
        "View": "view_sa_voucher_detail_allocation",
        "UseRecover": true,
        "Objects": []
      }
    ],
    "Links": [
      {
        "Type": "sa_invoice",
        "RefType": 3560,
        "RefTypeCategory": 356,
        "View": "view_sa_invoice",
        "Reference": {
          "Type": "sa_invoice_reference",
          "Key": "referencef_id",
          "MainKey": "voucher_refid",
          "SubKey": "sa_invoice_refid",
          "ReferenceKey": "voucher_refid",
          "IsUsingSubQuery": true
        },
        "Object": {
          "account_object_id": "2e09a780-d17f-47a7-bff2-eef23ea3b9b6",
          "display_on_book": 0,
          "reftype": 3560,
          "inv_date": "2026-01-10T10:00:31.000Z",
          "is_posted": true,
          "include_invoice": 1,
          "exchange_rate": 1,
          "account_object_name": "Khách lẻ",
          "account_object_address": "C39 Geleximco C",
          "payment_method": "TM/CK",
          "discount_type": 0,
          "state": 1,
          "account_object_code": "KLE",
          "is_invoice_machine": false,
          "employee_id": "98a6e8e5-5aeb-42f7-8238-8fbd1e34b1b3",
          "employee_name": "CÔNG TY CỔ PHẦN ĐẦU TƯ GIÁO DỤC BẮC TRUNG NAM",
          "outward_exported_status": 1,
          "refdate": "2026-01-10T10:00:31.000Z",
          "posted_date": "2026-01-10T10:00:31.000Z",
          "is_invoice_exported": true,
          "is_paid": false,
          "is_sale_with_outward": true,
          "total_sale_amount_oc": 51000,
          "total_sale_amount": 51000,
          "total_amount_oc": 53152,
          "total_amount": 53152,
          "total_discount_amount_oc": 0,
          "total_discount_amount": 0,
          "total_vat_amount_oc": 2152,
          "total_vat_amount": 2152,
          "total_export_tax_amount_oc": 0,
          "total_export_tax_amount": 0,
          "caba_amount": 0,
          "caba_amount_oc": 0,
          "refno_finance": "BH00300",
          "payer": "Chúc",
          "journal_memo": "Bán hàng Khách lẻ",
          "currency_id": "VND",
          "paid_type": 0,
          "discount_rate_voucher": 0,
          "employee_code": "NV000001",
          "attachment_id_list_data": [],
          "is_follows_406": false,
          "tax_reduction_type": 0,
          "is_tax_reduction_type_43": false,
          "invoiced_amount": 0,
          "invoice_exported_status": 0,
          "dav_using_permision": true,
          "is_discount_invoice_123": false,
          "invoiveRefids": [],
          "invoiveRefidsDelete": [],
          "caba_refno_finance": "XK00304",
          "old_data": null,
          "MappingEinvoiceObjectList": []
        }
      },
      {
        "Type": "in_outward",
        "RefType": 2020,
        "RefTypeCategory": 202,
        "Key": "",
        "Reference": {
          "Type": "sale_outward_reference",
          "Key": "referencef_id",
          "MainKey": "sa_voucher_refid",
          "SubKey": "in_outward_refid"
        },
        "Object": {
          "account_object_id": "2e09a780-d17f-47a7-bff2-eef23ea3b9b6",
          "account_object_name": "Khách lẻ",
          "account_object_code": "KLE",
          "account_object_address": "C39 Geleximco C",
          "journal_memo": "Xuất kho bán hàng Khách lẻ",
          "employee_id": "98a6e8e5-5aeb-42f7-8238-8fbd1e34b1b3",
          "employee_code": "NV000001",
          "employee_name": "CÔNG TY CỔ PHẦN ĐẦU TƯ GIÁO DỤC BẮC TRUNG NAM",
          "display_on_book": 0,
          "reftype": 2020,
          "posted_date": "2026-01-10T10:00:31.000Z",
          "refdate": "2026-01-10T10:00:31.000Z",
          "in_reforder": "2026-01-10T10:00:31.000Z",
          "is_sale_with_outward": true,
          "total_amount_finance": 0,
          "refno_finance": "XK00304",
          "state": 1,
          "ik_stock_ids": "51a49d53-2fea-4e56-8cdd-bf41af64a0bf",
          "is_sale_with_outward_enum": 1,
          "old_data": null
        }
      }
    ],
    "Object": {
      "account_object_id": "2e09a780-d17f-47a7-bff2-eef23ea3b9b6",
      "account_object_name": "Khách lẻ",
      "account_object_address": "C39 Geleximco C",
      "employee_id": "98a6e8e5-5aeb-42f7-8238-8fbd1e34b1b3",
      "employee_name": "CÔNG TY CỔ PHẦN ĐẦU TƯ GIÁO DỤC BẮC TRUNG NAM",
      "display_on_book": 0,
      "reftype": 3530,
      "outward_exported_status": 1,
      "refdate": "2026-01-10T10:00:31.000Z",
      "posted_date": "2026-01-10T10:00:31.000Z",
      "include_invoice": 1,
      "is_invoice_exported": true,
      "is_paid": false,
      "is_sale_with_outward": true,
      "exchange_rate": 1,
      "total_sale_amount_oc": 51000,
      "total_sale_amount": 51000,
      "total_amount_oc": 53152,
      "total_amount": 53152,
      "total_discount_amount_oc": 0,
      "total_discount_amount": 0,
      "total_vat_amount_oc": 2152,
      "total_vat_amount": 2152,
      "total_export_tax_amount_oc": 0,
      "total_export_tax_amount": 0,
      "caba_amount": 0,
      "caba_amount_oc": 0,
      "refno_finance": "BH00300",
      "payer": "Chúc",
      "journal_memo": "Bán hàng Khách lẻ",
      "currency_id": "VND",
      "paid_type": 0,
      "state": 1,
      "discount_type": 0,
      "account_object_code": "KLE",
      "discount_rate_voucher": 0,
      "employee_code": "NV000001",
      "attachment_id_list_data": [],
      "is_follows_406": false,
      "tax_reduction_type": 0,
      "is_tax_reduction_type_43": false,
      "invoiced_amount": 53152,
      "invoice_exported_status": 0,
      "dav_using_permision": true,
      "is_discount_invoice_123": false,
      "invoiveRefids": [],
      "invoiveRefidsDelete": [],
      "caba_refno_finance": "XK00304",
      "inv_date": "2026-01-10T10:00:31.000Z",
      "lstContractRefid": "",
      "lstContractRefidMaster": ""
    },
    "auditing_log": {
      "id": null,
      "tenant_id": null,
      "refid": null,
      "user_id": null,
      "reftype": 3530,
      "login_name": null,
      "ip": null,
      "action": 1,
      "action_name": "Thêm",
      "reference": "Số chứng từ: BH00300\nSố phiếu xuất: XK00304\n",
      "description": "- Số dòng: 2 \n- Tổng số tiền: 53.152.",
      "time": null,
      "state": 1,
      "object_name": "Bán hàng hóa trong nước chưa thu tiền",
      "branch_name": "CÔNG TY CỔ PHẦN ĐẦU TƯ GIÁO DỤC BẮC TRUNG NAM",
      "is_inserting_log_into_another_db": null,
      "log_database_id": null,
      "securityactionid": null,
      "record_type": null,
      "index": 1,
      "isAuditingLog": true,
      "masterDescription": [],
      "isMultiMaster": false,
      "detailDescription": {
        "insert": [],
        "update": [],
        "delete": [],
        "custom": []
      }
    },
    "BypassValidate": {},
    "OptionForSave": {
      "PostAfterSave": true,
      "IsQuickEdit": false,
      "FormState": "Add"
    }
  }
];